name: Fraud Detection CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        
    - name: Download dataset
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        pip install kaggle
        mkdir -p ~/.kaggle
        echo '{"username":"$KAGGLE_USERNAME","key":"$KAGGLE_KEY"}' > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json
        kaggle datasets download -d mlg-ulb/creditcardfraud -p data/
        unzip data/creditcardfraud.zip -d data/
    
    - name: Run tests
      run: |
        pytest tests/